const ERROR_STATE = 3;
const SAVE_BUT_NOT_APPROVE_STATE = 2;
const SUCCESS_STATE = 1;
const WAITING_STATE = 0;
const SUSPEND_STATE = 4;

export { ERROR_STATE, SAVE_BUT_NOT_APPROVE_STATE, SUCCESS_STATE, WAITING_STATE, SUSPEND_STATE };